### PR TITLE
React 15.0.1

### PR DESCRIPTION
**Pull request by islemaster**
Adaptation of https://github.com/casesandberg/react-color/pull/132 with fixes for failing tests and warnings.

### CODE REVIEW

**Comment by Hamms** [comment]
Seems straightforward enough. Do we have a feeling for how comprehensive the tests are? How thoroughly manually tested is this?

**Comment by islemaster** [comment]
I haven't manually tested yet.  Let me do some work on that.  Unit tests seem pretty thin to me, but that's just at a glance:

```
╰○ npm test

> react-color@2.0.0 test /home/brad/Projects/react-color
> npm run unit-test


> react-color@2.0.0 unit-test /home/brad/Projects/react-color
> ./node_modules/mocha/bin/mocha "test/**/*.test.js" --compilers js:babel-register



  Chrome
    ✓ should call onChange when handleChange is called (40ms)

  ChromeFields
    ✓ should change state.view to hex when alpha is 1
    ✓ should return hex when handleChange is fired
    ✓ should return objects that are keyed with the color key when handleChange is fired
    ✓ should shuffle through view value when clicking on toggle
    ✓ should change state.view to rgb if the props change and alpha isn’t 1

  Compact
    ✓ should be able to take custom swatches
    ✓ should pass up data on change

  CompactColor
    ✓ should call onClick when a color is clicked on and pass back color

  Photoshop
    ✓ should fire onAccept when "OK" is clicked
    ✓ should fire onCancel when "Cancel" is clicked
    ✓ should pass up data onChange

  PhotoshopFields
    ✓ should pass up hex data onChange

  Sketch
    ✓ should pass up data onChange (42ms)

  SketchFields
    ✓ should pass up data onChange

  SketchPresetColors
    ✓ should pass up data onClick
    ✓ should pass back up a color when clicked

  Slider
    ✓ should pass up data onChange

  SliderSwatch
    ✓ should pass up data with handleClick
    ✓ should pass up data when clicked

  SliderSwatches
    ✓ should pass up data onClick

  Swatches
    ✓ should pass up data onChange (124ms)
    ✓ should render SwatchesGroup for each top-level array passed to props.colors

  SwatchesColor
    ✓ should pass the color back up when clicked

  SwatchesGroup
    ✓ should pass up data onClick
    ✓ should render SwatchesGroup for each top-level array passed to props.colors


  26 passing (434ms)
```

**Comment by islemaster** [comment]
Actually, manual testing is pretty easy (though what to cover isn't documented so well).  Running `npm run docs` fires up a local docs server, serving the same contents as [casesandberg.github.io/react-color](http://casesandberg.github.io/react-color/) with all seven color-picker variations running at the top of the page.

Everything appears to be functioning properly.  There's a lot of log noise on master (much of it from webpack hot module replacement) but there are some additional errors on this branch, similar to the warnings I eliminated from the tests.

screenshot from 2016-05-02 14-40-17

I'll get the warnings back down to what's already on the master branch and then ping you for another look.

**Comment by islemaster** [comment]
Okay, I've eliminated all the React property warnings on the demo page that were introduced by the update.  The color pickers all work as expected AFAICT.

My remaining concern is that to fix several of these warnings I had to make changes to both the `src` and `lib` versions of files in the `modules` folder, e.g.

```
modules/react-material-design/src/components/Tile.js
modules/react-material-design/lib/components/Tile.js
```

The `lib` folder definitely appears to be a built version of the `src` folder (it's run through babel, for example), but I can't find the command that's normally used to do this - `npm run lib` doesn't seem to do the trick.  I've gone ahead and made the needed changes by hand since they're fairly trivial, but that does worry me a bit.

Any other particular concerns?

**Comment by Hamms** [comment]
That seems perfectly reasonable; I assume we don't need to worry too much about sustainable development practices for a one-off fork.

This LGTM!

**Comment by jaeh** [comment]
```
npm run lib
```

 builds the library if i remember correctly.

thanks a lot for picking this up where i left it <3

**Pull request merged**
